// Social Media for Real Estate Brokers/react-app/src/assets/components/SignUp.tsx
function SignUp() {

    const handleSubmit = (event) => {
        event.preventDefault();

        const testData = {
            username: "u",
            password: "p",
            confirmPassword: "p"
        };

        // This is where I will submit the request to the Java server
        fetch('http://localhost:8081/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ testData })
        })
        .then (response => {
            console.log("HIT!");
            console.log(response);
        })
        .catch(error => {
            console.log("Sign-up failed")
            console.error('There was a problem with your fetch operation:', error);
        });
    };

    return (
        <>
        <h1>This Will Be the Sign-up Form</h1>
        <form onSubmit={handleSubmit}>
            <input type="text" placeholder="Username"></input>
            <br/>
            <input type="text" placeholder="Password"></input>
            <br/>
            <input type="text" placeholder="Confirm Password"></input>
            <br/>
            <input type="submit" id="submit"></input>
        </form>
        </>
    )
}

export default SignUp;

// Social Media for Real Estate Brokers/angular-app/src/app/sign-up.component.ts
import { Component } from "@angular/core";

import { SignupService } from '../services/sign-up.service';

@Component({
    selector: 'sign-up',
    templateUrl: './sign-up.component.html',
    styleUrls: ['./sign-up.component.css']
})
export class SignUpComponent {
    username: string = '';
    password: string = '';
    confirmPassword: string = '';

    constructor(private signupService: SignupService) {}

    onSubmit(event: Event) {
        event.preventDefault();  // Prevent default form submission

        if (this.password !== this.confirmPassword) {
            console.error('Passwords do not match');
            return;
        }

        const userData = {
            username: this.username,
            password: this.password
        }

        this.signupService.signUp(userData).subscribe({
            next: response => {
                console.log('Sign-up Successful!');
                console.log(response);
            },
            error: error => {
                console.log('Sign-up Failed!');
                console.log(error.status);
                console.log(error.error.error);
                console.error(error);
            }
        });
    }

}
<h1>This will be the Sign-up Component</h1>
<form (ngSubmit)="onSubmit($event)">
  <input type="text" placeholder="Username" [(ngModel)]="username" name="username" required />
  <input type="password" placeholder="Password" [(ngModel)]="password" name="password" required />
  <input type="password" placeholder="Confirm Password" [(ngModel)]="confirmPassword" name="confirmPassword" required />
  <input type="submit" value="Create Account" />
</form>
