// Social Media for Real Estate Brokers/angular-app/src/app/login.component.ts
import { Component } from "@angular/core";

import { LoginService } from "../services/login.service";

@Component({
    selector: 'login',
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.css']
})
export class LoginComponent {
    username: string = '';
    password: string = '';

    constructor(private loginService: LoginService) {}

    onSubmit(event: Event) {
        event.preventDefault();  // Prevent default form submission

        const userData = {
            username: this.username,
            password: this.password
        }

        this.loginService.signUp(userData).subscribe({
            next: response => {
                console.log('Login Successful!');
                console.log(response);
            },
            error: error => {
                console.log('Login Failed!');
                console.log(error.status);
                console.log(error.error.error);
                console.error(error);
            }
        });
    }
}

<h1>This is the Login Component</h1>
<form (ngSubmit)="onSubmit($event)">
  <input type="text" placeholder="Username" [(ngModel)]="username" name="username" required />
  <input type="password" placeholder="Password" [(ngModel)]="password" name="password" required />
  <input type="submit" value="Login" />
</form>

// Social Media for Real Estate Brokers/react-app/src/assets/components/Login.tsx
function Login() {

    const handleSubmit = (event) => {
        event.preventDefault();
        // This is where I will submit the request to the Java server
    };

    return (
        <>
        <h1>This Will Be the Login Form</h1>
        <form onSubmit={handleSubmit}>
            <input type="text" placeholder="Username"></input>
            <br/>
            <input type="text" placeholder="Password"></input>
            <br/>
            <input type="submit" id="submit"></input>
        </form>
        </>
    )
}

export default Login;
